<?php /** @var \ClawRock\BugHerd\Block\Script $block */ ?>
<script type="text/javascript">
    (function (d, t) {
        var bh = d.createElement(t), s = d.getElementsByTagName(t)[0];
        bh.type = 'text/javascript';
        bh.src = 'https://www.bugherd.com/sidebarv2.js?apikey=<?php /* @noEscape */ echo $block->getApiKey(); ?>';
        s.parentNode.insertBefore(bh, s);
    })(document, 'script');
</script>
